# Generated by Django 3.2.3 on 2021-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='died',
            field=models.DateField(default='1900-1-1'),
        ),
        migrations.AddField(
            model_name='actor',
            name='firstname',
            field=models.CharField(default='Andy', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(default=2, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='surname',
            field=models.CharField(default='Anonymus', max_length=40),
        ),
        migrations.AddField(
            model_name='actor',
            name='was_born',
            field=models.DateField(default='1900-1-1'),
        ),
    ]
