# Generated by Django 3.2.3 on 2021-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20210522_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='curriculum',
            field=models.TextField(default='lorem ipsum'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(default='USA', max_length=35),
        ),
    ]
